version: '3.8'
services:
  cups-airprint-foo2zjs:
    container_name: cups-airprint-foo2zjs
    image: ghcr.io/cornelcotoara/docker-cups-airprint-foo2zjs:master
    restart: unless-stopped
    network_mode: host
    environment:
      - CUPSADMIN=cupsadmin
      - CUPSPASSWORD=cups123
    volumes:
      - /opt/docker/cups-airprint-foo2zjs/config:/config
      - /opt/docker/cups-airprint-foo2zjs/services:/services
      - /var/run/dbus:/var/run/dbus:ro
    devices:
      - "/dev/bus:/dev/bus"
      - "/dev/usb:/dev/usb"
